spring:
  application:
    name: comunio-news
  datasource:
    url: jdbc:h2:file:./db/comunio-news;AUTO_SERVER=TRUE
    username: sa
  ai:
    google:
      genai:
        api-key: ${GOOGLE_GENAI_API_KEY}
        chat:
          options:
            model: gemini-3-flash-preview
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
management:
  endpoints:
    web:
      exposure:
        include:
        - scheduledTasks
        - quartz
  endpoint:
    quartz:
      show-values: always
logging:
  level:
    root: INFO
    org.springframework.context.event: DEBUG
    org.zalando.logbook: TRACE
comunio:
  cid: 13742756
  # BL season 2025/2026 => 2026
  season: 2026
  stats:
    base-url: https://stats.comunio.de
    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:147.0) Gecko/20100101 Firefox/147.0
    credentials:
      username: ${STATS_COMUNIO_USER}
      password: ${STATS_COMUNIO_PW}
logbook:
  format:
    style: http
  strategy: body-only-if-status-at-least
app:
  club-id-mapping:
    - name: BVB
      olid: 7
      cid: 5
    - name: BMG
      olid: 87
      cid: 3
    - name: VFB
      olid: 16
      cid: 14
    - name: TSG
      olid: 175
      cid: 62
    - name: WOB
      olid: 131
      cid: 12
    - name: SCF
      olid: 112
      cid: 21
    - name: FCA
      olid: 95
      cid: 68
    - name: SVW
      olid: 134
      cid: 6
    - name: KOE
      olid: 65
      cid: 13
    - name: FCU
      olid: 80
      cid: 109
    - name: HSV
      olid: 100
      cid: 4
    - name: SGE
      olid: 91
      cid: 9
    - name: RBL
      olid: 1635
      cid: 92
    - name: B04
      olid: 6
      cid: 8
    - name: M05
      olid: 81
      cid: 18
    - name: STP
      olid: 98
      cid: 25
    - name: FCH
      olid: 199
      cid: 110
    - name: FCB
      olid: 40
      cid: 1
