package de.openligadb.api

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.springframework.http.ResponseEntity
import org.springframework.messaging.converter.JacksonJsonMessageConverter
import org.springframework.web.client.RestClient
import org.springframework.web.client.RestClientResponseException
import de.openligadb.model.BlTableTeam
import de.openligadb.model.GoalGetter
import de.openligadb.model.Group
import de.openligadb.model.League
import de.openligadb.model.Match
import de.openligadb.model.ResultInfo
import de.openligadb.model.Sport
import de.openligadb.model.Team
import org.springframework.http.converter.json.JsonbHttpMessageConverter
import org.springframework.messaging.converter.JsonbMessageConverter
import java.time.OffsetDateTime

/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
class MatchdataApi(client: RestClient) : ApiClient(client) {

    constructor(baseUrl: String) : this(
        RestClient.builder()
        .baseUrl(baseUrl)
        .build()
    )


    @Throws(RestClientResponseException::class)
    fun getavailablegroupsLeagueShortcutLeagueSeasonGet(leagueShortcut: String, leagueSeason: Int): List<Group> {
        val result = getavailablegroupsLeagueShortcutLeagueSeasonGetWithHttpInfo(leagueShortcut = leagueShortcut, leagueSeason = leagueSeason)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getavailablegroupsLeagueShortcutLeagueSeasonGetWithHttpInfo(leagueShortcut: String, leagueSeason: Int): ResponseEntity<List<Group>> {
        val localVariableConfig = getavailablegroupsLeagueShortcutLeagueSeasonGetRequestConfig(leagueShortcut = leagueShortcut, leagueSeason = leagueSeason)
        return request<Unit, List<Group>>(
            localVariableConfig
        )
    }

    fun getavailablegroupsLeagueShortcutLeagueSeasonGetRequestConfig(leagueShortcut: String, leagueSeason: Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
            "leagueShortcut" to leagueShortcut,
            "leagueSeason" to leagueSeason,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getavailablegroups/{leagueShortcut}/{leagueSeason}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getavailableleaguesGet(): List<League> {
        val result = getavailableleaguesGetWithHttpInfo()
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getavailableleaguesGetWithHttpInfo(): ResponseEntity<List<League>> {
        val localVariableConfig = getavailableleaguesGetRequestConfig()
        return request<Unit, List<League>>(
            localVariableConfig
        )
    }

    fun getavailableleaguesGetRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getavailableleagues",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getavailablesportsGet(): List<Sport> {
        val result = getavailablesportsGetWithHttpInfo()
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getavailablesportsGetWithHttpInfo(): ResponseEntity<List<Sport>> {
        val localVariableConfig = getavailablesportsGetRequestConfig()
        return request<Unit, List<Sport>>(
            localVariableConfig
        )
    }

    fun getavailablesportsGetRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getavailablesports",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getavailableteamsLeagueShortcutLeagueSeasonGet(leagueShortcut: String, leagueSeason: Int): List<Team> {
        val result = getavailableteamsLeagueShortcutLeagueSeasonGetWithHttpInfo(leagueShortcut = leagueShortcut, leagueSeason = leagueSeason)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getavailableteamsLeagueShortcutLeagueSeasonGetWithHttpInfo(leagueShortcut: String, leagueSeason: Int): ResponseEntity<List<Team>> {
        val localVariableConfig = getavailableteamsLeagueShortcutLeagueSeasonGetRequestConfig(leagueShortcut = leagueShortcut, leagueSeason = leagueSeason)
        return request<Unit, List<Team>>(
            localVariableConfig
        )
    }

    fun getavailableteamsLeagueShortcutLeagueSeasonGetRequestConfig(leagueShortcut: String, leagueSeason: Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
            "leagueShortcut" to leagueShortcut,
            "leagueSeason" to leagueSeason,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getavailableteams/{leagueShortcut}/{leagueSeason}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getbltableLeagueShortcutLeagueSeasonGet(leagueShortcut: String, leagueSeason: Int): List<BlTableTeam> {
        val result = getbltableLeagueShortcutLeagueSeasonGetWithHttpInfo(leagueShortcut = leagueShortcut, leagueSeason = leagueSeason)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getbltableLeagueShortcutLeagueSeasonGetWithHttpInfo(leagueShortcut: String, leagueSeason: Int): ResponseEntity<List<BlTableTeam>> {
        val localVariableConfig = getbltableLeagueShortcutLeagueSeasonGetRequestConfig(leagueShortcut = leagueShortcut, leagueSeason = leagueSeason)
        return request<Unit, List<BlTableTeam>>(
            localVariableConfig
        )
    }

    fun getbltableLeagueShortcutLeagueSeasonGetRequestConfig(leagueShortcut: String, leagueSeason: Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
            "leagueShortcut" to leagueShortcut,
            "leagueSeason" to leagueSeason,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getbltable/{leagueShortcut}/{leagueSeason}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getcurrentgroupLeagueShortcutGet(leagueShortcut: String): Group {
        val result = getcurrentgroupLeagueShortcutGetWithHttpInfo(leagueShortcut = leagueShortcut)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getcurrentgroupLeagueShortcutGetWithHttpInfo(leagueShortcut: String): ResponseEntity<Group> {
        val localVariableConfig = getcurrentgroupLeagueShortcutGetRequestConfig(leagueShortcut = leagueShortcut)
        return request<Unit, Group>(
            localVariableConfig
        )
    }

    fun getcurrentgroupLeagueShortcutGetRequestConfig(leagueShortcut: String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
            "leagueShortcut" to leagueShortcut,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getcurrentgroup/{leagueShortcut}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getgoalgettersLeagueShortcutLeagueSeasonGet(leagueShortcut: String, leagueSeason: Int): List<GoalGetter> {
        val result = getgoalgettersLeagueShortcutLeagueSeasonGetWithHttpInfo(leagueShortcut = leagueShortcut, leagueSeason = leagueSeason)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getgoalgettersLeagueShortcutLeagueSeasonGetWithHttpInfo(leagueShortcut: String, leagueSeason: Int): ResponseEntity<List<GoalGetter>> {
        val localVariableConfig = getgoalgettersLeagueShortcutLeagueSeasonGetRequestConfig(leagueShortcut = leagueShortcut, leagueSeason = leagueSeason)
        return request<Unit, List<GoalGetter>>(
            localVariableConfig
        )
    }

    fun getgoalgettersLeagueShortcutLeagueSeasonGetRequestConfig(leagueShortcut: String, leagueSeason: Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
            "leagueShortcut" to leagueShortcut,
            "leagueSeason" to leagueSeason,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getgoalgetters/{leagueShortcut}/{leagueSeason}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getgrouptableLeagueShortcutLeagueSeasonGet(leagueShortcut: String, leagueSeason: Int): List<BlTableTeam> {
        val result = getgrouptableLeagueShortcutLeagueSeasonGetWithHttpInfo(leagueShortcut = leagueShortcut, leagueSeason = leagueSeason)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getgrouptableLeagueShortcutLeagueSeasonGetWithHttpInfo(leagueShortcut: String, leagueSeason: Int): ResponseEntity<List<BlTableTeam>> {
        val localVariableConfig = getgrouptableLeagueShortcutLeagueSeasonGetRequestConfig(leagueShortcut = leagueShortcut, leagueSeason = leagueSeason)
        return request<Unit, List<BlTableTeam>>(
            localVariableConfig
        )
    }

    fun getgrouptableLeagueShortcutLeagueSeasonGetRequestConfig(leagueShortcut: String, leagueSeason: Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
            "leagueShortcut" to leagueShortcut,
            "leagueSeason" to leagueSeason,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getgrouptable/{leagueShortcut}/{leagueSeason}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getlastchangedateLeagueShortcutLeagueSeasonGroupOrderIdGet(leagueShortcut: String, leagueSeason: Int, groupOrderId: Int): OffsetDateTime {
        val result = getlastchangedateLeagueShortcutLeagueSeasonGroupOrderIdGetWithHttpInfo(leagueShortcut = leagueShortcut, leagueSeason = leagueSeason, groupOrderId = groupOrderId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getlastchangedateLeagueShortcutLeagueSeasonGroupOrderIdGetWithHttpInfo(leagueShortcut: String, leagueSeason: Int, groupOrderId: Int): ResponseEntity<OffsetDateTime> {
        val localVariableConfig = getlastchangedateLeagueShortcutLeagueSeasonGroupOrderIdGetRequestConfig(leagueShortcut = leagueShortcut, leagueSeason = leagueSeason, groupOrderId = groupOrderId)
        return request<Unit, OffsetDateTime>(
            localVariableConfig
        )
    }

    fun getlastchangedateLeagueShortcutLeagueSeasonGroupOrderIdGetRequestConfig(leagueShortcut: String, leagueSeason: Int, groupOrderId: Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
            "leagueShortcut" to leagueShortcut,
            "leagueSeason" to leagueSeason,
            "groupOrderId" to groupOrderId,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getlastchangedate/{leagueShortcut}/{leagueSeason}/{groupOrderId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getlastmatchbyleagueshortcutLeagueShortcutGet(leagueShortcut: String): Match {
        val result = getlastmatchbyleagueshortcutLeagueShortcutGetWithHttpInfo(leagueShortcut = leagueShortcut)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getlastmatchbyleagueshortcutLeagueShortcutGetWithHttpInfo(leagueShortcut: String): ResponseEntity<Match> {
        val localVariableConfig = getlastmatchbyleagueshortcutLeagueShortcutGetRequestConfig(leagueShortcut = leagueShortcut)
        return request<Unit, Match>(
            localVariableConfig
        )
    }

    fun getlastmatchbyleagueshortcutLeagueShortcutGetRequestConfig(leagueShortcut: String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
            "leagueShortcut" to leagueShortcut,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getlastmatchbyleagueshortcut/{leagueShortcut}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getlastmatchbyleagueteamLeagueIdTeamIdGet(leagueId: Int, teamId: Int): Match {
        val result = getlastmatchbyleagueteamLeagueIdTeamIdGetWithHttpInfo(leagueId = leagueId, teamId = teamId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getlastmatchbyleagueteamLeagueIdTeamIdGetWithHttpInfo(leagueId: Int, teamId: Int): ResponseEntity<Match> {
        val localVariableConfig = getlastmatchbyleagueteamLeagueIdTeamIdGetRequestConfig(leagueId = leagueId, teamId = teamId)
        return request<Unit, Match>(
            localVariableConfig
        )
    }

    fun getlastmatchbyleagueteamLeagueIdTeamIdGetRequestConfig(leagueId: Int, teamId: Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
            "leagueId" to leagueId,
            "teamId" to teamId,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getlastmatchbyleagueteam/{leagueId}/{teamId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getmatchdataLeagueShortcutLeagueSeasonGet(leagueShortcut: String, leagueSeason: Int): List<Match> {
        val result = getmatchdataLeagueShortcutLeagueSeasonGetWithHttpInfo(leagueShortcut = leagueShortcut, leagueSeason = leagueSeason)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getmatchdataLeagueShortcutLeagueSeasonGetWithHttpInfo(leagueShortcut: String, leagueSeason: Int): ResponseEntity<List<Match>> {
        val localVariableConfig = getmatchdataLeagueShortcutLeagueSeasonGetRequestConfig(leagueShortcut = leagueShortcut, leagueSeason = leagueSeason)
        return request<Unit, List<Match>>(
            localVariableConfig
        )
    }

    fun getmatchdataLeagueShortcutLeagueSeasonGetRequestConfig(leagueShortcut: String, leagueSeason: Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
            "leagueShortcut" to leagueShortcut,
            "leagueSeason" to leagueSeason,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getmatchdata/{leagueShortcut}/{leagueSeason}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getmatchdataLeagueShortcutLeagueSeasonGroupOrderIdGet(leagueShortcut: String, leagueSeason: Int, groupOrderId: Int): List<Match> {
        val result = getmatchdataLeagueShortcutLeagueSeasonGroupOrderIdGetWithHttpInfo(leagueShortcut = leagueShortcut, leagueSeason = leagueSeason, groupOrderId = groupOrderId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getmatchdataLeagueShortcutLeagueSeasonGroupOrderIdGetWithHttpInfo(leagueShortcut: String, leagueSeason: Int, groupOrderId: Int): ResponseEntity<List<Match>> {
        val localVariableConfig = getmatchdataLeagueShortcutLeagueSeasonGroupOrderIdGetRequestConfig(leagueShortcut = leagueShortcut, leagueSeason = leagueSeason, groupOrderId = groupOrderId)
        return request<Unit, List<Match>>(
            localVariableConfig
        )
    }

    fun getmatchdataLeagueShortcutLeagueSeasonGroupOrderIdGetRequestConfig(leagueShortcut: String, leagueSeason: Int, groupOrderId: Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
            "leagueShortcut" to leagueShortcut,
            "leagueSeason" to leagueSeason,
            "groupOrderId" to groupOrderId,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getmatchdata/{leagueShortcut}/{leagueSeason}/{groupOrderId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getmatchdataLeagueShortcutLeagueSeasonTeamFilterstringGet(leagueShortcut: String, leagueSeason: Int, teamFilterstring: String): List<Match> {
        val result = getmatchdataLeagueShortcutLeagueSeasonTeamFilterstringGetWithHttpInfo(leagueShortcut = leagueShortcut, leagueSeason = leagueSeason, teamFilterstring = teamFilterstring)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getmatchdataLeagueShortcutLeagueSeasonTeamFilterstringGetWithHttpInfo(leagueShortcut: String, leagueSeason: Int, teamFilterstring: String): ResponseEntity<List<Match>> {
        val localVariableConfig = getmatchdataLeagueShortcutLeagueSeasonTeamFilterstringGetRequestConfig(leagueShortcut = leagueShortcut, leagueSeason = leagueSeason, teamFilterstring = teamFilterstring)
        return request<Unit, List<Match>>(
            localVariableConfig
        )
    }

    fun getmatchdataLeagueShortcutLeagueSeasonTeamFilterstringGetRequestConfig(leagueShortcut: String, leagueSeason: Int, teamFilterstring: String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
            "leagueShortcut" to leagueShortcut,
            "leagueSeason" to leagueSeason,
            "teamFilterstring" to teamFilterstring,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getmatchdata/{leagueShortcut}/{leagueSeason}/{teamFilterstring}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getmatchdataMatchIdGet(matchId: Int): Match {
        val result = getmatchdataMatchIdGetWithHttpInfo(matchId = matchId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getmatchdataMatchIdGetWithHttpInfo(matchId: Int): ResponseEntity<Match> {
        val localVariableConfig = getmatchdataMatchIdGetRequestConfig(matchId = matchId)
        return request<Unit, Match>(
            localVariableConfig
        )
    }

    fun getmatchdataMatchIdGetRequestConfig(matchId: Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
            "matchId" to matchId,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getmatchdata/{matchId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getmatchdataTeamId1TeamId2Get(teamId1: Int, teamId2: Int): List<Match> {
        val result = getmatchdataTeamId1TeamId2GetWithHttpInfo(teamId1 = teamId1, teamId2 = teamId2)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getmatchdataTeamId1TeamId2GetWithHttpInfo(teamId1: Int, teamId2: Int): ResponseEntity<List<Match>> {
        val localVariableConfig = getmatchdataTeamId1TeamId2GetRequestConfig(teamId1 = teamId1, teamId2 = teamId2)
        return request<Unit, List<Match>>(
            localVariableConfig
        )
    }

    fun getmatchdataTeamId1TeamId2GetRequestConfig(teamId1: Int, teamId2: Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
            "teamId1" to teamId1,
            "teamId2" to teamId2,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getmatchdata/{teamId1}/{teamId2}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getmatchesbyteamTeamFilterstringWeekCountPastWeekCountFutureGet(teamFilterstring: String, weekCountPast: Int, weekCountFuture: Int): List<Match> {
        val result = getmatchesbyteamTeamFilterstringWeekCountPastWeekCountFutureGetWithHttpInfo(teamFilterstring = teamFilterstring, weekCountPast = weekCountPast, weekCountFuture = weekCountFuture)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getmatchesbyteamTeamFilterstringWeekCountPastWeekCountFutureGetWithHttpInfo(teamFilterstring: String, weekCountPast: Int, weekCountFuture: Int): ResponseEntity<List<Match>> {
        val localVariableConfig = getmatchesbyteamTeamFilterstringWeekCountPastWeekCountFutureGetRequestConfig(teamFilterstring = teamFilterstring, weekCountPast = weekCountPast, weekCountFuture = weekCountFuture)
        return request<Unit, List<Match>>(
            localVariableConfig
        )
    }

    fun getmatchesbyteamTeamFilterstringWeekCountPastWeekCountFutureGetRequestConfig(teamFilterstring: String, weekCountPast: Int, weekCountFuture: Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
            "teamFilterstring" to teamFilterstring,
            "weekCountPast" to weekCountPast,
            "weekCountFuture" to weekCountFuture,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getmatchesbyteam/{teamFilterstring}/{weekCountPast}/{weekCountFuture}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getmatchesbyteamidTeamIdWeekCountPastWeekCountFutureGet(teamId: Int, weekCountPast: Int, weekCountFuture: Int): List<Match> {
        val result = getmatchesbyteamidTeamIdWeekCountPastWeekCountFutureGetWithHttpInfo(teamId = teamId, weekCountPast = weekCountPast, weekCountFuture = weekCountFuture)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getmatchesbyteamidTeamIdWeekCountPastWeekCountFutureGetWithHttpInfo(teamId: Int, weekCountPast: Int, weekCountFuture: Int): ResponseEntity<List<Match>> {
        val localVariableConfig = getmatchesbyteamidTeamIdWeekCountPastWeekCountFutureGetRequestConfig(teamId = teamId, weekCountPast = weekCountPast, weekCountFuture = weekCountFuture)
        return request<Unit, List<Match>>(
            localVariableConfig
        )
    }

    fun getmatchesbyteamidTeamIdWeekCountPastWeekCountFutureGetRequestConfig(teamId: Int, weekCountPast: Int, weekCountFuture: Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
            "teamId" to teamId,
            "weekCountPast" to weekCountPast,
            "weekCountFuture" to weekCountFuture,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getmatchesbyteamid/{teamId}/{weekCountPast}/{weekCountFuture}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getnextmatchbyleagueshortcutLeagueShortcutGet(leagueShortcut: String): Match {
        val result = getnextmatchbyleagueshortcutLeagueShortcutGetWithHttpInfo(leagueShortcut = leagueShortcut)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getnextmatchbyleagueshortcutLeagueShortcutGetWithHttpInfo(leagueShortcut: String): ResponseEntity<Match> {
        val localVariableConfig = getnextmatchbyleagueshortcutLeagueShortcutGetRequestConfig(leagueShortcut = leagueShortcut)
        return request<Unit, Match>(
            localVariableConfig
        )
    }

    fun getnextmatchbyleagueshortcutLeagueShortcutGetRequestConfig(leagueShortcut: String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
            "leagueShortcut" to leagueShortcut,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getnextmatchbyleagueshortcut/{leagueShortcut}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getnextmatchbyleagueteamLeagueIdTeamIdGet(leagueId: Int, teamId: Int): Match {
        val result = getnextmatchbyleagueteamLeagueIdTeamIdGetWithHttpInfo(leagueId = leagueId, teamId = teamId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getnextmatchbyleagueteamLeagueIdTeamIdGetWithHttpInfo(leagueId: Int, teamId: Int): ResponseEntity<Match> {
        val localVariableConfig = getnextmatchbyleagueteamLeagueIdTeamIdGetRequestConfig(leagueId = leagueId, teamId = teamId)
        return request<Unit, Match>(
            localVariableConfig
        )
    }

    fun getnextmatchbyleagueteamLeagueIdTeamIdGetRequestConfig(leagueId: Int, teamId: Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
            "leagueId" to leagueId,
            "teamId" to teamId,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getnextmatchbyleagueteam/{leagueId}/{teamId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    @Throws(RestClientResponseException::class)
    fun getresultinfosLeagueIdGet(leagueId: Int): ResultInfo {
        val result = getresultinfosLeagueIdGetWithHttpInfo(leagueId = leagueId)
        return result.body!!
    }

    @Throws(RestClientResponseException::class)
    fun getresultinfosLeagueIdGetWithHttpInfo(leagueId: Int): ResponseEntity<ResultInfo> {
        val localVariableConfig = getresultinfosLeagueIdGetRequestConfig(leagueId = leagueId)
        return request<Unit, ResultInfo>(
            localVariableConfig
        )
    }

    fun getresultinfosLeagueIdGetRequestConfig(leagueId: Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "text/plain, application/json, text/json"

        val params = mutableMapOf<String, Any>(
            "leagueId" to leagueId,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/getresultinfos/{leagueId}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

}