/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.openligadb.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param teamInfoId 
 * @param teamName 
 * @param shortName 
 * @param teamIconUrl 
 * @param points 
 * @param opponentGoals 
 * @param goals 
 * @param matches 
 * @param won 
 * @param lost 
 * @param draw 
 * @param goalDiff 
 */


data class BlTableTeam (

    @get:JsonProperty("teamInfoId")
    val teamInfoId: Int? = null,

    @get:JsonProperty("teamName")
    val teamName: String? = null,

    @get:JsonProperty("shortName")
    val shortName: String? = null,

    @get:JsonProperty("teamIconUrl")
    val teamIconUrl: String? = null,

    @get:JsonProperty("points")
    val points: Int? = null,

    @get:JsonProperty("opponentGoals")
    val opponentGoals: Int? = null,

    @get:JsonProperty("goals")
    val goals: Int? = null,

    @get:JsonProperty("matches")
    val matches: Int? = null,

    @get:JsonProperty("won")
    val won: Int? = null,

    @get:JsonProperty("lost")
    val lost: Int? = null,

    @get:JsonProperty("draw")
    val draw: Int? = null,

    @get:JsonProperty("goalDiff")
    val goalDiff: Int? = null

) {


}

