/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.openligadb.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param name 
 */


data class GlobalResultInfo (

    @get:JsonProperty("id")
    val id: Int? = null,

    @get:JsonProperty("name")
    val name: String? = null

) {


}

