/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.openligadb.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param goalGetterId 
 * @param goalGetterName 
 * @param goalCount 
 */


data class GoalGetter (

    @get:JsonProperty("goalGetterId")
    val goalGetterId: Int? = null,

    @get:JsonProperty("goalGetterName")
    val goalGetterName: String? = null,

    @get:JsonProperty("goalCount")
    val goalCount: Int? = null

) {


}

