/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.openligadb.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param goalID 
 * @param scoreTeam1 
 * @param scoreTeam2 
 * @param matchMinute 
 * @param goalGetterID 
 * @param goalGetterName 
 * @param isPenalty 
 * @param isOwnGoal 
 * @param isOvertime 
 * @param comment 
 */


data class Goal (

    @get:JsonProperty("goalID")
    val goalID: Int? = null,

    @get:JsonProperty("scoreTeam1")
    val scoreTeam1: Int? = null,

    @get:JsonProperty("scoreTeam2")
    val scoreTeam2: Int? = null,

    @get:JsonProperty("matchMinute")
    val matchMinute: Int? = null,

    @get:JsonProperty("goalGetterID")
    val goalGetterID: Int? = null,

    @get:JsonProperty("goalGetterName")
    val goalGetterName: String? = null,

    @get:JsonProperty("isPenalty")
    val isPenalty: Boolean? = null,

    @get:JsonProperty("isOwnGoal")
    val isOwnGoal: Boolean? = null,

    @get:JsonProperty("isOvertime")
    val isOvertime: Boolean? = null,

    @get:JsonProperty("comment")
    val comment: String? = null

) {


}

