/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.openligadb.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param groupName 
 * @param groupOrderID 
 * @param groupID 
 */


data class Group (

    @get:JsonProperty("groupName")
    val groupName: String? = null,

    @get:JsonProperty("groupOrderID")
    val groupOrderID: Int? = null,

    @get:JsonProperty("groupID")
    val groupID: Int? = null

) {


}

