/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.openligadb.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param leagueId 
 * @param leagueName 
 * @param leagueShortcut 
 * @param leagueSeason 
 * @param sport 
 */


data class League (

    @get:JsonProperty("leagueId")
    val leagueId: Int? = null,

    @get:JsonProperty("leagueName")
    val leagueName: String? = null,

    @get:JsonProperty("leagueShortcut")
    val leagueShortcut: String? = null,

    @get:JsonProperty("leagueSeason")
    val leagueSeason: String? = null,

    @get:JsonProperty("sport")
    val sport: Sport? = null

) {


}

