/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.openligadb.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param locationID 
 * @param locationCity 
 * @param locationStadium 
 */


data class Location (

    @get:JsonProperty("locationID")
    val locationID: Int? = null,

    @get:JsonProperty("locationCity")
    val locationCity: String? = null,

    @get:JsonProperty("locationStadium")
    val locationStadium: String? = null

) {


}

