/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.openligadb.model

import com.fasterxml.jackson.annotation.JsonProperty
import java.time.Instant
import java.time.LocalDateTime
import java.time.OffsetDateTime

/**
 * 
 *
 * @param matchID 
 * @param matchDateTime 
 * @param timeZoneID 
 * @param leagueId 
 * @param leagueName 
 * @param leagueSeason 
 * @param leagueShortcut 
 * @param matchDateTimeUTC 
 * @param group 
 * @param team1 
 * @param team2 
 * @param lastUpdateDateTime 
 * @param matchIsFinished 
 * @param matchResults 
 * @param goals 
 * @param location 
 * @param numberOfViewers 
 */


data class Match (

    @get:JsonProperty("matchID")
    val matchID: Int? = null,

    @get:JsonProperty("matchDateTime")
    val matchDateTime: LocalDateTime? = null,

    @get:JsonProperty("timeZoneID")
    val timeZoneID: String? = null,

    @get:JsonProperty("leagueId")
    val leagueId: Int? = null,

    @get:JsonProperty("leagueName")
    val leagueName: String? = null,

    @get:JsonProperty("leagueSeason")
    val leagueSeason: Int? = null,

    @get:JsonProperty("leagueShortcut")
    val leagueShortcut: String? = null,

    @get:JsonProperty("matchDateTimeUTC")
    val matchDateTimeUTC: OffsetDateTime? = null,

    @get:JsonProperty("group")
    val group: Group? = null,

    @get:JsonProperty("team1")
    val team1: Team? = null,

    @get:JsonProperty("team2")
    val team2: Team? = null,

    @get:JsonProperty("lastUpdateDateTime")
    val lastUpdateDateTime: LocalDateTime? = null,

    @get:JsonProperty("matchIsFinished")
    val matchIsFinished: Boolean? = null,

    @get:JsonProperty("matchResults")
    val matchResults: List<MatchResult>? = null,

    @get:JsonProperty("goals")
    val goals: List<Goal>? = null,

    @get:JsonProperty("location")
    val location: Location? = null,

    @get:JsonProperty("numberOfViewers")
    val numberOfViewers: Int? = null

) {


}

