/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.openligadb.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param resultID 
 * @param resultName 
 * @param pointsTeam1 
 * @param pointsTeam2 
 * @param resultOrderID 
 * @param resultTypeID 
 * @param resultDescription 
 */


data class MatchResult (

    @get:JsonProperty("resultID")
    val resultID: Int? = null,

    @get:JsonProperty("resultName")
    val resultName: String? = null,

    @get:JsonProperty("pointsTeam1")
    val pointsTeam1: Int? = null,

    @get:JsonProperty("pointsTeam2")
    val pointsTeam2: Int? = null,

    @get:JsonProperty("resultOrderID")
    val resultOrderID: Int? = null,

    @get:JsonProperty("resultTypeID")
    val resultTypeID: Int? = null,

    @get:JsonProperty("resultDescription")
    val resultDescription: String? = null

) {


}

