/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.openligadb.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param name 
 * @param description 
 * @param orderId 
 * @param globalResultInfo 
 */


data class ResultInfo (

    @get:JsonProperty("id")
    val id: Int? = null,

    @get:JsonProperty("name")
    val name: String? = null,

    @get:JsonProperty("description")
    val description: String? = null,

    @get:JsonProperty("orderId")
    val orderId: Int? = null,

    @get:JsonProperty("globalResultInfo")
    val globalResultInfo: GlobalResultInfo? = null

) {


}

