/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.openligadb.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param sportId 
 * @param sportName 
 */


data class Sport (

    @get:JsonProperty("sportId")
    val sportId: Int? = null,

    @get:JsonProperty("sportName")
    val sportName: String? = null

) {


}

