/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.openligadb.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param teamId 
 * @param teamName 
 * @param shortName 
 * @param teamIconUrl 
 * @param teamGroupName 
 */


data class Team (

    @get:JsonProperty("teamId")
    val teamId: Int? = null,

    @get:JsonProperty("teamName")
    val teamName: String? = null,

    @get:JsonProperty("shortName")
    val shortName: String? = null,

    @get:JsonProperty("teamIconUrl")
    val teamIconUrl: String? = null,

    @get:JsonProperty("teamGroupName")
    val teamGroupName: String? = null

) {


}

